### ISSUE TITLE
Make photos work w/o credits

### ISSUE THREAD

**Issue by liddiard** [dailybruin/interactive.2014.wake-of-the-storm#2]
Photo credits are not necessary because they are included in the story byline. However, removal of photo credits which result in the photo caption being empty causes `Liquid Exception: undefined method 'gsub' for nil:NilClass`

**Comment by liddiard** [comment]
@nbedi says it's fine as is

**Comment by blutz** [comment]
@liddiard that story byline is enormous lol. And if you want to get rid of a caption you can just take "caption" out of the liquid template tag
